version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore TestAPI/TestAPI.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build TestAPI/TestAPI.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish TestAPI/TestAPI.csproj -c Release -o ./publish
      - echo "Listing published files..."
      - ls -l ./publish  # List files inside publish directory
      - find ./publish -type f  # Recursively list all files

artifacts:
  files:
    - '**/*'
  base-directory: ./publish  